# Generated by Django 5.2.3 on 2025-06-25 09:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='League Name')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='League Level')),
                ('current_season_year', models.PositiveIntegerField(default=2025, verbose_name='Current Season Year')),
                ('status', models.CharField(choices=[('PRE_SEASON', 'Pre-Season'), ('REGULAR_SEASON', 'Regular Season'), ('PLAYOFFS', 'Playoffs'), ('OFF_SEASON', 'Off-Season')], default='PRE_SEASON', max_length=20)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Team Name')),
                ('coach_name', models.CharField(max_length=100, verbose_name='Coach Name')),
                ('arena_name', models.CharField(max_length=100, verbose_name='Arena Name')),
                ('home_jersey_color', models.CharField(max_length=50, verbose_name='Home Jersey Color')),
                ('away_jersey_color', models.CharField(max_length=50, verbose_name='Away Jersey Color')),
                ('titles', models.PositiveIntegerField(default=0, verbose_name='Championships')),
                ('budget', models.PositiveIntegerField(default=1000000, verbose_name='Budget (in $)')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='TopFiveBack.league', verbose_name='League')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Manager (User)')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('position_primary', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2, verbose_name='Primary Position')),
                ('position_secondary', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2, null=True)),
                ('height', models.FloatField(verbose_name='Height (meters)')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('shooting_2p', models.FloatField(default=60.0)),
                ('shooting_3p', models.FloatField(default=60.0)),
                ('free_throws', models.FloatField(default=60.0)),
                ('rebound_def', models.FloatField(default=60.0)),
                ('rebound_off', models.FloatField(default=60.0)),
                ('passing', models.FloatField(default=60.0)),
                ('blocking', models.FloatField(default=60.0)),
                ('defense', models.FloatField(default=60.0)),
                ('game_iq', models.FloatField(default=60.0)),
                ('speed', models.FloatField(default=60.0)),
                ('jumping', models.FloatField(default=60.0)),
                ('strength', models.FloatField(default=60.0)),
                ('stamina', models.FloatField(default=60.0)),
                ('fitness', models.PositiveIntegerField(default=100)),
                ('is_injured', models.BooleanField(default=False)),
                ('injury_duration', models.PositiveIntegerField(default=0)),
                ('is_retired', models.BooleanField(default=False)),
                ('contract_years', models.PositiveIntegerField(default=1)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='TopFiveBack.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('match_round', models.IntegerField()),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('current_quarter', models.IntegerField(default=1)),
                ('game_clock', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='TopFiveBack.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='TopFiveBack.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='TopFiveBack.team')),
                ('possession_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possession_matches', to='TopFiveBack.team')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2025, verbose_name='Season Year')),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points_for', models.PositiveIntegerField(default=0, verbose_name='Points Scored')),
                ('points_against', models.PositiveIntegerField(default=0, verbose_name='Points Conceded')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='TopFiveBack.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='TopFiveBack.team')),
            ],
            options={
                'verbose_name': 'Team Season Stats',
                'verbose_name_plural': 'Team Season Stats',
                'ordering': ['-wins', '-points_for'],
                'unique_together': {('team', 'league', 'season')},
            },
        ),
    ]
