# Generated by Django 5.2.3 on 2025-06-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='League Name')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='League Level')),
                ('current_season_year', models.PositiveIntegerField(default=2025, verbose_name='Current Season Year')),
                ('status', models.CharField(choices=[('PRE_SEASON', 'Pre-Season'), ('REGULAR_SEASON', 'Regular Season'), ('PLAYOFFS', 'Playoffs'), ('OFF_SEASON', 'Off-Season')], default='PRE_SEASON', max_length=20)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Team Name')),
                ('coach_name', models.CharField(max_length=100, verbose_name='Coach Name')),
                ('arena_name', models.CharField(max_length=100, verbose_name='Arena Name')),
                ('home_jersey_color', models.CharField(max_length=50, verbose_name='Home Jersey Color')),
                ('away_jersey_color', models.CharField(max_length=50, verbose_name='Away Jersey Color')),
                ('titles', models.PositiveIntegerField(default=0, verbose_name='Championships')),
                ('budget', models.PositiveIntegerField(default=1000000, verbose_name='Budget (in $)')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='TopFiveBack.league', verbose_name='League')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Manager (User)')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('position_primary', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2, verbose_name='Primary Position')),
                ('position_secondary', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2, null=True, verbose_name='Secondary Position')),
                ('height', models.FloatField(verbose_name='Height (meters)')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('shooting_2p', models.IntegerField(default=60, verbose_name='2-Point Shooting')),
                ('shooting_3p', models.IntegerField(default=60, verbose_name='3-Point Shooting')),
                ('free_throws', models.IntegerField(default=60, verbose_name='Free Throws')),
                ('rebound_def', models.IntegerField(default=60, verbose_name='Defensive Rebound')),
                ('rebound_off', models.IntegerField(default=60, verbose_name='Offensive Rebound')),
                ('passing', models.IntegerField(default=60, verbose_name='Passing')),
                ('blocking', models.IntegerField(default=60, verbose_name='Blocking')),
                ('defense', models.IntegerField(default=60, verbose_name='Defense')),
                ('game_iq', models.IntegerField(default=60, verbose_name='Game IQ')),
                ('speed', models.IntegerField(default=60, verbose_name='Speed')),
                ('jumping', models.IntegerField(default=60, verbose_name='Jumping')),
                ('strength', models.IntegerField(default=60, verbose_name='Strength')),
                ('stamina', models.IntegerField(default=60, verbose_name='Stamina')),
                ('fitness', models.PositiveIntegerField(default=100, verbose_name='Fitness')),
                ('is_injured', models.BooleanField(default=False, verbose_name='Is Injured')),
                ('injury_duration', models.PositiveIntegerField(default=0, verbose_name='Injury Duration (days)')),
                ('is_retired', models.BooleanField(default=False, verbose_name='Is Retired')),
                ('contract_years', models.PositiveIntegerField(default=1, verbose_name='Contract Years')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='TopFiveBack.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
