# Generated by Django 5.2.3 on 2025-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_on_transfer_list',
            field=models.BooleanField(default=False, help_text='If checked, this player will appear on the transfer market even if they have a team.', verbose_name='On Transfer List'),
        ),
        migrations.AddField(
            model_name='player',
            name='market_value',
            field=models.PositiveIntegerField(default=500000, verbose_name='Market Value ($)'),
        ),
    ]
