# Generated by Django 5.2.3 on 2025-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blocking',
            field=models.FloatField(default=60.0, verbose_name='Blocking'),
        ),
        migrations.AlterField(
            model_name='player',
            name='defense',
            field=models.FloatField(default=60.0, verbose_name='Defense'),
        ),
        migrations.AlterField(
            model_name='player',
            name='free_throws',
            field=models.FloatField(default=60.0, verbose_name='Free Throws'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_iq',
            field=models.FloatField(default=60.0, verbose_name='Game IQ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumping',
            field=models.FloatField(default=60.0, verbose_name='Jumping'),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.FloatField(default=60.0, verbose_name='Passing'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebound_def',
            field=models.FloatField(default=60.0, verbose_name='Defensive Rebound'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebound_off',
            field=models.FloatField(default=60.0, verbose_name='Offensive Rebound'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shooting_2p',
            field=models.FloatField(default=60.0, verbose_name='2-Point Shooting'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shooting_3p',
            field=models.FloatField(default=60.0, verbose_name='3-Point Shooting'),
        ),
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.FloatField(default=60.0, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.FloatField(default=60.0, verbose_name='Stamina'),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.FloatField(default=60.0, verbose_name='Strength'),
        ),
    ]
