# Generated by Django 5.2.3 on 2025-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0002_alter_player_blocking_alter_player_defense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='current_season_year',
            field=models.PositiveIntegerField(default=1, verbose_name='Current Season Year'),
        ),
    ]
