# Generated by Django 5.2.3 on 2025-06-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0002_player_is_on_transfer_list_player_market_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='market_value',
        ),
    ]
