# Generated by Django 5.2.3 on 2025-06-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0002_player_is_on_transfer_list_player_market_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_c', to='TopFiveBack.player')),
                ('pf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_pf', to='TopFiveBack.player')),
                ('pg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_pg', to='TopFiveBack.player')),
                ('sf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_sf', to='TopFiveBack.player')),
                ('sg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_sg', to='TopFiveBack.player')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='TopFiveBack.team')),
            ],
        ),
    ]
