# Generated by Django 5.2.3 on 2025-07-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0003_teamlineup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamLineup',
        ),
    ]
