# Generated by Django 5.2.3 on 2025-06-23 16:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0003_alter_league_current_season_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('match_round', models.IntegerField()),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('current_quarter', models.IntegerField(default=1)),
                ('game_clock', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='TopFiveBack.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='TopFiveBack.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='TopFiveBack.league')),
                ('possession_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possession_matches', to='TopFiveBack.team')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
