# Generated by Django 5.2.3 on 2025-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0003_remove_player_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('BENCH', 'Bench'), ('RESERVE', 'Reserve')], default='RESERVE', max_length=10, verbose_name='Player Role'),
        ),
    ]
