# Generated by Django 5.2.3 on 2025-07-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0004_delete_teamlineup'),
        ('TopFiveBack', '0005_player_assigned_minutes_player_offensive_role'),
    ]

    operations = [
    ]
