# Generated by Django 5.2.3 on 2025-07-03 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0006_merge_20250702_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='defensive_aggressiveness',
            field=models.PositiveIntegerField(default=3, verbose_name='Aggressiveness (1-5)'),
        ),
        migrations.AddField(
            model_name='team',
            name='defensive_stopper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='TopFiveBack.player', verbose_name='Defensive Stopper'),
        ),
        migrations.AddField(
            model_name='team',
            name='go_to_guy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='TopFiveBack.player', verbose_name='Go-To Guy'),
        ),
        migrations.AddField(
            model_name='team',
            name='offensive_focus',
            field=models.CharField(choices=[('INSIDE', 'Inside Focus'), ('OUTSIDE', 'Outside Focus')], default='OUTSIDE', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='pace',
            field=models.PositiveIntegerField(default=3, verbose_name='Pace (1-5)'),
        ),
    ]
