# Generated by Django 5.2.3 on 2025-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0007_team_defensive_aggressiveness_team_defensive_stopper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='offensive_focus_slider',
            field=models.PositiveIntegerField(default=3, verbose_name='Offensive Focus Slider (1-5)'),
        ),
    ]
