# Generated by Django 5.2.3 on 2025-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopFiveBack', '0008_team_offensive_focus_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='asking_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Asking Price'),
        ),
    ]
